$schema: vscode://schemas/color-theme
author: Andrew R. King
name: Retro Future
semanticClass: theme.retrofuture
type: dark
tokenColors:
  # -----------------------------------------------------------------------------
  # L1
  # -----------------------------------------------------------------------------
  - scope: keyword, storage
    settings:
      foreground: _orange
      fontStyle: bold

  - scope: punctuation
    settings:
      foreground: _base-gray

  - scope: comment
    settings:
      foreground: _dark-gray
      fontStyle: italic

  - scope: variable
    settings:
      foreground: _white

  - scope: string
    settings:
      foreground: _light-green

  # -----------------------------------------------------------------------------
  # L2
  # -----------------------------------------------------------------------------
  - scope: storage.modifier
    settings:
      foreground: _orange
      fontStyle: bold

  - scope: entity.other
    settings:
      foreground: _white

  - scope: string.unquoted
    settings:
      foreground: _light-pink

  - scope: constant.numeric
    settings:
      foreground: _cyan

  - scope: constant.language
    settings:
      foreground: _light-green

  - scope: constant.character, constant.other
    settings:
      foreground: _light-green

  - scope: support.function
    settings:
      foreground: _blue

  - scope: support.type, support.constant
    settings:
      foreground: _light-blue

  # -----------------------------------------------------------------------------
  # L3
  # -----------------------------------------------------------------------------
  - scope: meta.brace.square, meta.brace.round, keyword.operator.assignment, storage.type.function.arrow, keyword.operator.comparison, keyword.operator.arithmetic, keyword.operator.relational, keyword.operator.increment, keyword.operator.decrement, keyword.operator.ternary, keyword.operator.bitwise
    settings:
      foreground: _base-gray

  - scope: punctuation.definition.comment
    settings:
      foreground: _dark-gray
      fontStyle: italic

  - scope: constant.language.boolean
    settings:
      foreground: _orange
      fontStyle: bold

  - scope: support.variable.dom, support.class.console
    settings:
      foreground: _white

  - scope: punctuation.definition.string
    settings:
      foreground: _light-green

  - scope: keyword.control.import, keyword.control.from, keyword.control.as
    settings:
      foreground: _magenta
      fontStyle: bold

  - scope: keyword.control.export, entity.name.class
    settings:
      foreground: _light-indigo
      fontStyle: bold

  - scope: entity.other.inherited-class, entity.name.tag, entity.other.attribute-name, punctuation.definition.tag
    settings:
      foreground: _light-indigo

  - scope: support.type.property-name
    settings:
      foreground: _light-blue

  - scope: entity.name.function, punctuation.definition.template-expression, punctuation.definition.template-expression, constant.character.escape
    settings:
      foreground: _blue

  - scope: support.function.console
    settings:
      foreground: _light-yellow
      fontStyle: bold

  - scope: variable.other.property, support.variable.property
    settings:
      foreground: _light-pink

  - scope: support.class.builtin, entity.name.type
    settings:
      foreground: _light-magenta

  - scope: support.class.component
    settings:
      foreground: _light-magenta
      fontStyle: italic

  - scope: variable.language.this
    settings:
      foreground: _blue
      fontStyle: bold

  - scope: variable.language.super
    settings:
      foreground: _blue
      fontStyle: bold

  - scope: entity.other.attribute-name
    settings:
      foreground: _orange

  - scope: punctuation.definition.directive, constant.other.caps, support.type.exception, variable.other.constant
    settings:
      foreground: _magenta

  # -----------------------------------------------------------------------------
  # L4
  # -----------------------------------------------------------------------------
  - scope: storage.type.function.arrow
    settings:
      foreground: _base-gray

  - scope: support.variable.property.dom, support.variable.property.process
    settings:
      foreground: _light-yellow
      fontStyle: bold

  - scope: variable.other.object.property
    settings:
      foreground: _light-pink

  - scope: support.type.object.module
    settings:
      foreground: _light-indigo
      fontStyle: bold

  - scope: variable.other.constant.property
    settings:
      foreground: _light-magenta

  - scope: punctuation.support.type.property-name
    settings:
      foreground: _light-blue

  - scope: constant.character.escape.continuation
    settings:
      foreground: _light-green

  # -----------------------------------------------------------------------------
  # Deprecate this shit
  # -----------------------------------------------------------------------------
  - scope: invalid
    settings:
      fontStyle: ""
      foreground: "#F1ADD2"

  - scope: invalid.deprecated
    settings:
      foreground: "#B2AFF0"

  - scope: token.info-token
    settings:
      foreground: "#6796e6"

  - scope: token.warn-token
    settings:
      foreground: "#cd9731"

  - scope: token.error-token
    settings:
      foreground: "#f44747"

  - scope: token.debug-token
    settings:
      foreground: "#b267e6"
