# -----------------------------------------------------------------------------
# Makefile
# -----------------------------------------------------------------------------
- scope: variable.other.makefile
  settings:
    foreground: _blue

- scope: punctuation.definition.variable.makefile
  settings:
    foreground: _light-green

- scope: entity.name.function.target.makefile, variable.language.makefile
  settings:
    foreground: _magenta

- scope: support.function.call.makefile
  settings:
    foreground: _light-yellow
